
version: '3.3'
services:
  webliferay-database:
    image: "mysql:5.5.62"
    container_name: webliferay-db
    environment:
      - MYSQL_DATABASE=lportal
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=dxpcloud
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    volumes:
      - type: volume
        source: webliferay-database-data
        target: /var/lib/mysql
      - type: bind
        source: ./database/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d

volumes:
  webliferay-database-data:

